import type { ComponentLibraryItem } from "../types/pcb";

export const COMPONENT_LIBRARY: ComponentLibraryItem[] = [
  // Passives
  {
    id: "resistor",
    name: "Resistor",
    category: "Passives",
    symbol: "R",
    width: 3,
    height: 1,
    color: "#c8a96e",
  },
  {
    id: "capacitor",
    name: "Capacitor",
    category: "Passives",
    symbol: "C",
    width: 2,
    height: 2,
    color: "#6ea8c8",
  },
  {
    id: "inductor",
    name: "Inductor",
    category: "Passives",
    symbol: "L",
    width: 3,
    height: 1,
    color: "#c8a96e",
  },
  {
    id: "crystal",
    name: "Crystal",
    category: "Passives",
    symbol: "XTAL",
    width: 2,
    height: 3,
    color: "#b0b0c8",
  },

  // Semiconductors
  {
    id: "diode",
    name: "Diode",
    category: "Semiconductors",
    symbol: "D",
    width: 2,
    height: 1,
    color: "#c87070",
  },
  {
    id: "led",
    name: "LED",
    category: "Semiconductors",
    symbol: "LED",
    width: 2,
    height: 1,
    color: "#70c870",
  },
  {
    id: "npn",
    name: "NPN Transistor",
    category: "Semiconductors",
    symbol: "NPN",
    width: 2,
    height: 3,
    color: "#c8a070",
  },
  {
    id: "pnp",
    name: "PNP Transistor",
    category: "Semiconductors",
    symbol: "PNP",
    width: 2,
    height: 3,
    color: "#c8a070",
  },
  {
    id: "vreg",
    name: "Voltage Regulator",
    category: "Semiconductors",
    symbol: "VR",
    width: 2,
    height: 3,
    color: "#9070c8",
  },

  // ICs
  {
    id: "ic_dip8",
    name: "IC DIP-8",
    category: "ICs",
    symbol: "IC8",
    width: 4,
    height: 5,
    color: "#404050",
  },
  {
    id: "ic_dip14",
    name: "IC DIP-14",
    category: "ICs",
    symbol: "IC14",
    width: 4,
    height: 8,
    color: "#404050",
  },
  {
    id: "ic_dip16",
    name: "IC DIP-16",
    category: "ICs",
    symbol: "IC16",
    width: 4,
    height: 9,
    color: "#404050",
  },

  // Connectors
  {
    id: "conn_2pin",
    name: "Connector 2-pin",
    category: "Connectors",
    symbol: "J2",
    width: 2,
    height: 2,
    color: "#70a870",
  },
  {
    id: "conn_4pin",
    name: "Connector 4-pin",
    category: "Connectors",
    symbol: "J4",
    width: 2,
    height: 4,
    color: "#70a870",
  },
  {
    id: "conn_8pin",
    name: "Connector 8-pin",
    category: "Connectors",
    symbol: "J8",
    width: 2,
    height: 8,
    color: "#70a870",
  },
  {
    id: "pushbutton",
    name: "Push Button",
    category: "Connectors",
    symbol: "SW",
    width: 2,
    height: 2,
    color: "#c87070",
  },
  {
    id: "switch",
    name: "Switch",
    category: "Connectors",
    symbol: "SW2",
    width: 3,
    height: 2,
    color: "#c87070",
  },

  // Tesla Coil components
  {
    id: "ne555",
    name: "NE555 Timer",
    category: "ICs",
    symbol: "NE555",
    width: 4,
    height: 5,
    color: "#404050",
  },
  {
    id: "cap_ceramic_100nf",
    name: "Cap 100nF",
    category: "Passives",
    symbol: "C100n",
    width: 2,
    height: 2,
    color: "#6ea8c8",
  },
  {
    id: "cap_ceramic_10nf",
    name: "Cap 10nF",
    category: "Passives",
    symbol: "C10n",
    width: 2,
    height: 2,
    color: "#6ea8c8",
  },
  {
    id: "cap_elec_100uf",
    name: "Cap 100µF",
    category: "Passives",
    symbol: "C100u",
    width: 2,
    height: 2,
    color: "#6ea8c8",
  },
  {
    id: "pot_p1",
    name: "Pot P1 (ON)",
    category: "Passives",
    symbol: "P1",
    width: 3,
    height: 1,
    color: "#c8a96e",
  },
  {
    id: "pot_p2",
    name: "Pot P2 (OFF)",
    category: "Passives",
    symbol: "P2",
    width: 3,
    height: 1,
    color: "#c8a96e",
  },
  {
    id: "npn_power",
    name: "NPN Power Q1",
    category: "Semiconductors",
    symbol: "Q1",
    width: 2,
    height: 3,
    color: "#c8a070",
  },
  {
    id: "screw_term_2pin",
    name: "Screw Terminal",
    category: "Connectors",
    symbol: "TERM",
    width: 2,
    height: 2,
    color: "#70a870",
  },
  {
    id: "switch_spst",
    name: "Switch S1",
    category: "Connectors",
    symbol: "S1",
    width: 3,
    height: 2,
    color: "#c87070",
  },
  {
    id: "switch_timer",
    name: "Timer Switch S2",
    category: "Connectors",
    symbol: "S2",
    width: 3,
    height: 2,
    color: "#c87070",
  },
];

export const COMPONENT_CATEGORIES: Array<{
  name: string;
  items: ComponentLibraryItem[];
}> = [
  {
    name: "Passives",
    items: COMPONENT_LIBRARY.filter((c) => c.category === "Passives"),
  },
  {
    name: "Semiconductors",
    items: COMPONENT_LIBRARY.filter((c) => c.category === "Semiconductors"),
  },
  {
    name: "ICs",
    items: COMPONENT_LIBRARY.filter((c) => c.category === "ICs"),
  },
  {
    name: "Connectors",
    items: COMPONENT_LIBRARY.filter((c) => c.category === "Connectors"),
  },
];

export function getComponentById(id: string): ComponentLibraryItem | undefined {
  return COMPONENT_LIBRARY.find((c) => c.id === id);
}
