/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Component {
  'id' : bigint,
  'rotation' : Rotation,
  'name' : string,
  'position' : Position,
}
export interface PCBDesign {
  'name' : string,
  'createdAt' : bigint,
  'components' : Array<Component>,
  'updatedAt' : bigint,
}
export interface Position { 'x' : number, 'y' : number }
export type Rotation = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDesign' : ActorMethod<[string], undefined>,
  'getBoardstoreKeys' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDesigns' : ActorMethod<[], Array<string>>,
  'loadDesign' : ActorMethod<[string], PCBDesign>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDesign' : ActorMethod<[PCBDesign], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];