/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Rotation = IDL.Int;
export const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const Component = IDL.Record({
  'id' : IDL.Nat,
  'rotation' : Rotation,
  'name' : IDL.Text,
  'position' : Position,
});
export const PCBDesign = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'components' : IDL.Vec(Component),
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDesign' : IDL.Func([IDL.Text], [], []),
  'getBoardstoreKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDesigns' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'loadDesign' : IDL.Func([IDL.Text], [PCBDesign], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDesign' : IDL.Func([PCBDesign], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Rotation = IDL.Int;
  const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const Component = IDL.Record({
    'id' : IDL.Nat,
    'rotation' : Rotation,
    'name' : IDL.Text,
    'position' : Position,
  });
  const PCBDesign = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'components' : IDL.Vec(Component),
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDesign' : IDL.Func([IDL.Text], [], []),
    'getBoardstoreKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDesigns' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'loadDesign' : IDL.Func([IDL.Text], [PCBDesign], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDesign' : IDL.Func([PCBDesign], [], []),
  });
};

export const init = ({ IDL }) => { return []; };